### ISSUE TITLE
lambda 好像点击就不支持了

### ISSUE THREAD

**Issue by yanghuaangel** [harvie1208/TracePoint#2]
lambda 好像点击就不支持了

**Comment by harvie1208** [comment]
![image](https://user-images.githubusercontent.com/18163710/94504272-f82d2900-023a-11eb-908a-bb24b4efe77a.png)
这样写的吗，我试了可以的

**Comment by harvie1208** [comment]
@yanghuaangel 如果不行，可以贴一下代码，我看下

**Comment by yanghuaangel** [comment]
是这样写的，奇怪了，你这里是可以的？

**Comment by yanghuaangel** [comment]
```
                //点击事件
                if (interfaces!=null && interfaces.length>0){

                    MethodCode methodCode = InterceptEventConfig.interfaceMethods.get(nameDesc)
                    if(methodCode!=null){
                        mv.visitVarInsn(Opcodes.ALOAD, 1)
                        mv.visitMethodInsn(Opcodes.INVOKESTATIC, InterceptEventConfig.owner, methodCode.agentName, methodCode.agentDesc, false)
                    }
                }
```

感觉这里写的也有问题 interfaces 是接口，如果class没有实现接口，这里是null，都走不到了吧

还有库用的androidx的Activity不知道有没有影响。
<img width="689" alt="图片" src="https://user-images.githubusercontent.com/12743975/94506043-0ed57f00-023f-11eb-9508-999cd377ec4c.png">

这里是ASM 的字节码
<img width="614" alt="图片" src="https://user-images.githubusercontent.com/12743975/94506114-36c4e280-023f-11eb-98d2-90869a0ce758.png">

**Comment by harvie1208** [comment]
@yanghuaangel click事件底层实现基于接口的，与应用层是否实现无关，可以通过源码或字节码查看。刚测了下在androidX上的使用是有问题的，接下来几天会尽快兼容androidX，发布新版本

**Comment by yanghuaangel** [comment]
原因我找到了，
dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'


我把这个升级到这个版本就不行了，classpath 'com.android.tools.build:gradle:3.0.0' 
3.0.0就是可以的，应该是高版本的gradle 无法找到匿名内部类

**Comment by harvie1208** [comment]
@yanghuaangel 新版本0.2.0已支持androidx,详见更新记录说明
