### ISSUE TITLE
Fragment或者Activity中使用Kotlin

### ISSUE THREAD

**Issue by xuqinghao1991** [harvie1208/TracePoint#4]
请问我应该怎么修改来进行适配kotlin

**Comment by xzj2125123** [comment]
我在KOTLIN 版本版本使用  。生成的class 全部只有一个 包名，空类容，博主 有解决方法嘛

**Comment by xuqinghao1991** [comment]
How to use it in Kotlin?Thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "harvie1208/TracePoint"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午2:27
收件人:&nbsp;"harvie1208/TracePoint"<TracePoint@noreply.github.com&gt;;
抄送:&nbsp;"梦里看花"<1986345650@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [harvie1208/TracePoint] Fragment或者Activity中使用Kotlin (#4)





 
我在KOTLIN 版本版本使用  。生成的class 全部只有一个 包名，空类容，博主 有解决方法嘛

**Comment by harvie1208** [comment]
@xzj2125123 @xuqinghao1991 我晚些时间看一下，最近比较忙

**Comment by xuqinghao1991** [comment]
好的,多谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "harvie1208/TracePoint"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午2:57
收件人:&nbsp;"harvie1208/TracePoint"<TracePoint@noreply.github.com&gt;;
抄送:&nbsp;"梦里看花"<1986345650@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [harvie1208/TracePoint] Fragment或者Activity中使用Kotlin (#4)





 
@xzj2125123 @xuqinghao1991 我晚些时间看一下，最近比较忙

**Comment by harvie1208** [comment]
@xzj2125123 @xuqinghao1991 经测试，集成kotlin只需正常引入kotlin插件即可，生成内容只有包名不影响使用，如需要查看实际编译代码内容，请执行如下操作查看  Tools –> Kotlin –> Show Kotlin ByteCodes -> decompile
